FROM ubuntu:16.04

SHELL ["/bin/bash", "-c"]
ARG HTTP_RPOXY
ARG HTTPS_PROXY

RUN echo configured http/https proxy: $HOSNAME ${HTTP_PROXY}/${HTTPS_PROXY}

RUN if [ ! -z "$HTTP_PROXY" ]; then echo Acquire::http::proxy \"$HTTP_PROXY\"\; >> /etc/apt/apt.conf; fi
RUN if [ ! -z "$HTTPS_PROXY" ]; then echo Acquire::https::proxy \"$HTTPS_PROXY\"\; >> /etc/apt/apt.conf; fi
RUN cat /etc/apt/apt.conf

RUN apt-get update
RUN export http_proxy=$HTTP_PROXY && echo $http_proxy && apt-get install -y software-properties-common && add-apt-repository ppa:mraa/mraa && apt-get update
RUN apt-get install -y curl build-essential libssl-dev libupm-dev python-upm python3-upm upm-examples python
    
ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 6.17.1

RUN curl https://raw.githubusercontent.com/creationix/nvm/v0.30.1/install.sh | bash
RUN source $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

ADD ./scripts/upmth02sensor /app
RUN addgroup --gid 1001 agent && \
    adduser --uid 1001 agent --gid 1001

RUN chown -R agent /app

WORKDIR /app

RUN npm --force cache clean && npm install && npm install mraa  && npm install jsupm_th02 && npm install child_process

#USER agent # unfortunately the i2c device can only be read as root

EXPOSE 1884
EXPOSE 8000
EXPOSE 41234
EXPOSE 7070

ENTRYPOINT node /app/upmth02sensor.js
